---
- name: Quality of Life (workstation)
  hosts: all
  become: true
  vars_files:
    - "../common_vars.yml"
  tasks:
    - name: Install packages
      ansible.builtin.dnf5:
        name: tilix
        state: latest
    - name: Install flatpacks
      community.general.flatpak:
        name:
          - "com.mattjakeman.ExtensionManager"
          - "org.filezillaproject.Filezilla"
          - "com.discordapp.Discord"
    - name: Install firacode fonts
      notify: Refresh fonts
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/FiraCode.zip
        dest: /usr/local/share/fonts/
        remote_src: true
        owner: root
        role: root
        mode: "0644"
    - name: Configure tilix
      block:
        - name: Create tilix theme directory
          ansible.builtin.file:
            state: directory
            path: "{{ user_config_dir }}/tilix/schemes"
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: u=rw,g=rx,o=r
        - name: Copy tilix themes
          ansible.builtin.get_url:
            url: "https://raw.githubusercontent.com/catppuccin/tilix/refs/heads/main/themes/catppuccin-{{ item.theme }}.json"
            dest: "{{ user_config_dir }}/tilix/schemes"
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: u=rw,g=r,o=r
          loop:
            - { theme: "frappe" }
            - { theme: "latte" }
            - { theme: "macchiato" }
            - { theme: "mocha" }
    - name: Copy Astronvim config
      ansible.builtin.copy:
        src: nvim
        dest: "{{ user_config_dir }}/nvim"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: u=rw,g=r,o=r
        force: false
    - name: Configure grub
      block:
        - name: Extract grub theme
          ansible.builtin.unarchive:
            src: "./catppuccin-mocha-grub-theme.zip"
            dest: /usr/share/grub/themes/catppuccin-mocha
            owner: root
            group: root
            mode: u=rw,g=r,o=r
        - name: Set grub theme
          notify: Update grub
          ansible.builtin.lineinfile:
            path: /etc/default/grub
            search_string: "GRUB_THEME"
            line: 'GRUB_THEME="/usr/share/grub/themes/catppuccin-mocha/theme.txt"'
        - name: Disable grub console output
          notify: Update grub
          ansible.builtin.lineinfile:
            path: /etc/default/grub
            line: '# GRUB_TERMINAL_OUTPUT="console"'
            search_string: "GRUB_TERMINAL_OUTPUT"
  handlers:
    - name: Refresh fonts
      ansible.builtin.command: fc-cache -v
      register: output
      changed_when: output != 0
    - name: Update grub
      ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
      register: output
      changed_when: output != 0
