---
- name: Quality of Life (workstation)
  hosts: all
  become: true
  vars:
    user: "{{ ansible_env['SUDO_USER'] }}"
    user_home: "{{ ansible_env['PWD'] }}"
    user_zshrc: "{{ user_home }}/.zshrc"
    user_config_dir: "{{ user_home }}/.config"
  tasks:
    - name: Install all packages
      ansible.builtin.dnf5:
        name: tilix
        state: latest
    - name: Install firacode fonts
      notify: Refresh fonts
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/FiraCode.zip
        dest: /usr/local/share/fonts/
        remote_src: true
        owner: root
        role: root
        mode: "0644"
    - name: Configure tilix
      block:
        - name: Create tilix theme directory
          ansible.builtin.file:
            state: directory
            path: "{{ user_config_dir }}/tilix/schemes"
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: u=rw,g=rx,o=r
        - name: Copy tilix themes
          ansible.builtin.get_url:
            url: "https://raw.githubusercontent.com/catppuccin/tilix/refs/heads/main/themes/catppuccin-{{ item.theme }}.json"
            dest: "{{ user_config_dir }}/tilix/schemes"
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: u=rw,g=rw,o=r
          loop:
            - { theme: "frappe" }
            - { theme: "latte" }
            - { theme: "macchiato" }
            - { theme: "mocha" }
    - name: Copy Astronvim config
      ansible.builtin.copy:
        src: nvim
        dest: "{{ user_config_dir }}/nvim"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: u=rw,g=rw,o=r
        force: false
  handlers:
    - name: Refresh fonts
      ansible.builtin.command: fc-cache -v
      register: output
      changed_when: output != 0
